site_name: Radio Astronomy Playground Documentation
site_url: https://gemmadanks.github.io/radio-astronomy-playground/
repo_url: https://github.com/gemmadanks/radio-astronomy-playground
repo_name: radio-astronomy-playground

theme:
  name: "material"
  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: simple/rocket

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

markdown_extensions:
  - pymdownx.superfences:
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      default_handler: python
      locale: en
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true      # shows module name as heading
            show_root_full_path: true    # gives full module path
  - search
  - tags
  - panzoom

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gemmadanks

nav:
  - Home: index.md
  - Tutorials:
      - Overview: tutorials/index.md
  - How-To:
      - Overview: how-to/index.md
  - Reference: reference/index.md
  - Explanation:
      - Overview: explanation/index.md
  - Domain:
      - Overview: domain/index.md
  - Architecture:
      - Overview: architecture/index.md
      - ADRs: architecture/adr/index.md
  - Tags: tags.md

extra_javascript:
    - javascript/readthedocs.js
    - https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
